url: https://auranbuckles.com
enforce_ssl: auranbuckles.com

# Site settings
title:  Auran Buckles
header-img: assets/img/banner.jpg
img_path: /assets/img
author: Auran Buckles
email: auran59@gmail.com
copyright_name: auranbuckles.com
# description:
baseurl: "" # the subpath of your site, e.g. /blog
# twitter_username:
github_username:  auranbuckles
learn_profile: auranbuckles
linkedin_username: auranbuckles

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed, jekyll-compose, jekyll-sitemap]
